import { HugeiconsIcon } from "@hugeicons/react";
import { Add01Icon, Alert02Icon, ArrowDown01Icon, ArrowLeft01Icon, ArrowRight01Icon, BalloonIcon, BasketballIcon, BookOpen01Icon, Bookmark01Icon, BubbleChatIcon, Calendar01Icon, Calendar03Icon, Cancel01Icon, CancelCircleIcon, ChampionIcon, CheckmarkBadge01Icon, CheckmarkCircle02Icon, ChipIcon, Clock01Icon, CloudUploadIcon, Compass01Icon, ComputerIcon, Copy01Icon, Delete02Icon, DialpadSquare01Icon, Download01Icon, Facebook01Icon, FavouriteIcon, File01Icon, Film01Icon, Flag01Icon, GithubIcon, GlobalIcon, HelpCircleIcon, Home01Icon, HourglassIcon, Image01Icon, InformationCircleIcon, InstagramIcon, LanguageSquareIcon, Layers01Icon, Leaf01Icon, Link01Icon, Linkedin01Icon, Loading03Icon, Location01Icon, LockIcon, Logout01Icon, Mail01Icon, Maximize01Icon, Megaphone01Icon, Menu01Icon, Menu03Icon, MinusSignIcon, Moon02Icon, MoreHorizontalIcon, MoreVerticalIcon, MusicNote01Icon, Notification01Icon, PaintBoardIcon, PencilEdit01Icon, QrCodeIcon, RedoIcon, RefreshIcon, RestaurantIcon, RibbonIcon, Rocket01Icon, ScanIcon, SchoolIcon, Search01Icon, Settings02Icon, Share01Icon, Shield01Icon, Shirt01Icon, ShuffleIcon, SparklesIcon, Sun01Icon, Tag01Icon, TextBoldIcon, TextIcon, TextItalicIcon, Tick02Icon, Ticket01Icon, Timer01Icon, TwitterIcon, UndoIcon, UserAdd01Icon, UserGroupIcon, UserIcon, ViewIcon, ViewOffIcon } from "@hugeicons/core-free-icons";

const HugeIcons = { Add01Icon, Alert02Icon, ArrowDown01Icon, ArrowLeft01Icon, ArrowRight01Icon, BalloonIcon, BasketballIcon, BookOpen01Icon, Bookmark01Icon, BubbleChatIcon, Calendar01Icon, Calendar03Icon, Cancel01Icon, CancelCircleIcon, ChampionIcon, CheckmarkBadge01Icon, CheckmarkCircle02Icon, ChipIcon, Clock01Icon, CloudUploadIcon, Compass01Icon, ComputerIcon, Copy01Icon, Delete02Icon, DialpadSquare01Icon, Download01Icon, Facebook01Icon, FavouriteIcon, File01Icon, Film01Icon, Flag01Icon, GithubIcon, GlobalIcon, HelpCircleIcon, Home01Icon, HourglassIcon, Image01Icon, InformationCircleIcon, InstagramIcon, LanguageSquareIcon, Layers01Icon, Leaf01Icon, Link01Icon, Linkedin01Icon, Loading03Icon, Location01Icon, LockIcon, Logout01Icon, Mail01Icon, Maximize01Icon, Megaphone01Icon, Menu01Icon, Menu03Icon, MinusSignIcon, Moon02Icon, MoreHorizontalIcon, MoreVerticalIcon, MusicNote01Icon, Notification01Icon, PaintBoardIcon, PencilEdit01Icon, QrCodeIcon, RedoIcon, RefreshIcon, RestaurantIcon, RibbonIcon, Rocket01Icon, ScanIcon, SchoolIcon, Search01Icon, Settings02Icon, Share01Icon, Shield01Icon, Shirt01Icon, ShuffleIcon, SparklesIcon, Sun01Icon, Tag01Icon, TextBoldIcon, TextIcon, TextItalicIcon, Tick02Icon, Ticket01Icon, Timer01Icon, TwitterIcon, UndoIcon, UserAdd01Icon, UserGroupIcon, UserIcon, ViewIcon, ViewOffIcon };

// Compatibility layer for the project's previous icon names. All glyphs are
// rendered by Hugeicons, while call sites retain their familiar component API.
const iconMap = {
  AiFillCloseCircle: "CancelCircleIcon", AiOutlineEye: "ViewIcon", AiOutlineEyeInvisible: "ViewOffIcon", AiOutlineLoading: "Loading03Icon",
  IoAdd: "Add01Icon", IoAddOutline: "Add01Icon", IoArrowBack: "ArrowLeft01Icon", IoArrowBackOutline: "ArrowLeft01Icon", IoArrowForward: "ArrowRight01Icon", IoArrowRedoOutline: "RedoIcon", IoArrowUndoOutline: "UndoIcon",
  IoBalloonOutline: "BalloonIcon", IoBasketballOutline: "BasketballIcon", IoBookOutline: "BookOpen01Icon", IoBookmarkOutline: "Bookmark01Icon", IoCalendarClearOutline: "Calendar03Icon", IoCalendarOutline: "Calendar01Icon",
  IoChatbubbleEllipsesOutline: "BubbleChatIcon", IoCheckmarkCircle: "CheckmarkCircle02Icon", IoCheckmarkCircleOutline: "CheckmarkCircle02Icon", IoCheckmarkDoneOutline: "CheckmarkBadge01Icon",
  IoChevronBackOutline: "ArrowLeft01Icon", IoChevronDownOutline: "ArrowDown01Icon", IoChevronForwardOutline: "ArrowRight01Icon", IoClose: "Cancel01Icon", IoCloseCircle: "CancelCircleIcon", IoCloseCircleOutline: "CancelCircleIcon", IoCloseOutline: "Cancel01Icon",
  IoCloudUploadOutline: "CloudUploadIcon", IoColorPaletteOutline: "PaintBoardIcon", IoCompassOutline: "Compass01Icon", IoCopy: "Copy01Icon", IoCopyOutline: "Copy01Icon", IoCreateOutline: "PencilEdit01Icon", IoDocumentTextOutline: "File01Icon", IoDownloadOutline: "Download01Icon",
  IoEllipsisHorizontal: "MoreHorizontalIcon", IoEllipsisVertical: "MoreVerticalIcon", IoExpandOutline: "Maximize01Icon", IoEyeOutline: "ViewIcon", IoFilmOutline: "Film01Icon", IoFlagOutline: "Flag01Icon", IoGlobeOutline: "GlobalIcon", IoHardwareChipOutline: "ChipIcon", IoHeartOutline: "FavouriteIcon", IoHomeOutline: "Home01Icon", IoHourglassOutline: "HourglassIcon", IoImageOutline: "Image01Icon", IoKeypadOutline: "DialpadSquare01Icon", IoLanguageOutline: "LanguageSquareIcon", IoLayersOutline: "Layers01Icon", IoLeafOutline: "Leaf01Icon", IoLinkOutline: "Link01Icon", IoLocation: "Location01Icon", IoLocationOutline: "Location01Icon", IoLockClosedOutline: "LockIcon", IoLogOutOutline: "Logout01Icon",
  IoLogoFacebook: "Facebook01Icon", IoLogoLinkedin: "Linkedin01Icon", IoMailOutline: "Mail01Icon", IoMegaphoneOutline: "Megaphone01Icon", IoMoonOutline: "Moon02Icon", IoMusicalNotesOutline: "MusicNote01Icon", IoNotificationsOutline: "Notification01Icon", IoOptionsOutline: "Settings02Icon", IoPencil: "PencilEdit01Icon", IoPeopleOutline: "UserGroupIcon", IoPersonAddOutline: "UserAdd01Icon", IoPersonOutline: "UserIcon", IoPricetagOutline: "Tag01Icon", IoQrCodeOutline: "QrCodeIcon", IoRefreshOutline: "RefreshIcon", IoRemoveOutline: "MinusSignIcon", IoReorderThreeOutline: "Menu01Icon", IoRestaurantOutline: "RestaurantIcon", IoRibbonOutline: "RibbonIcon", IoRocketOutline: "Rocket01Icon", IoScanOutline: "ScanIcon", IoSchoolOutline: "SchoolIcon", IoSearchOutline: "Search01Icon", IoShareSocialOutline: "Share01Icon", IoShieldCheckmarkOutline: "Shield01Icon", IoShirtOutline: "Shirt01Icon", IoShuffleOutline: "ShuffleIcon", IoSparkles: "SparklesIcon", IoSunnyOutline: "Sun01Icon", IoTextOutline: "TextIcon", IoTicketOutline: "Ticket01Icon", IoTimeOutline: "Clock01Icon", IoTimerOutline: "Timer01Icon", IoTrashOutline: "Delete02Icon", IoTrophyOutline: "ChampionIcon", IoWarningOutline: "Alert02Icon",
  MdComputer: "ComputerIcon", MdFormatBold: "TextBoldIcon", MdFormatItalic: "TextItalicIcon", MdInfo: "InformationCircleIcon", MdLocationPin: "Location01Icon", MdOutlineArrowBack: "ArrowLeft01Icon",
  RiDownloadFill: "Download01Icon", RiGithubFill: "GithubIcon", RiInstagramFill: "InstagramIcon", RiInstagramLine: "InstagramIcon", RiMenu3Line: "Menu03Icon", RiTwitterFill: "TwitterIcon", RiTwitterLine: "TwitterIcon", TiTick: "Tick02Icon"
};

function makeIcon(name) {
  const icon = HugeIcons[iconMap[name]] || HugeIcons.HelpCircleIcon;
  const Component = ({ size, color = "currentColor", strokeWidth = 1.8, className, ...props }) => (
    <HugeiconsIcon icon={icon} size={size || "1em"} color={color} strokeWidth={strokeWidth} className={className} {...props} />
  );
  Component.displayName = name;
  return Component;
}

export const {
  AiFillCloseCircle, AiOutlineEye, AiOutlineEyeInvisible, AiOutlineLoading, IoAdd, IoAddOutline, IoArrowBack, IoArrowBackOutline, IoArrowForward, IoArrowRedoOutline, IoArrowUndoOutline, IoBalloonOutline, IoBasketballOutline, IoBookOutline, IoBookmarkOutline, IoCalendarClearOutline, IoCalendarOutline, IoChatbubbleEllipsesOutline, IoCheckmarkCircle, IoCheckmarkCircleOutline, IoCheckmarkDoneOutline, IoChevronBackOutline, IoChevronDownOutline, IoChevronForwardOutline, IoClose, IoCloseCircle, IoCloseCircleOutline, IoCloseOutline, IoCloudUploadOutline, IoColorPaletteOutline, IoCompassOutline, IoCopy, IoCopyOutline, IoCreateOutline, IoDocumentTextOutline, IoDownloadOutline, IoEllipsisHorizontal, IoEllipsisVertical, IoExpandOutline, IoEyeOutline, IoFilmOutline, IoFlagOutline, IoGlobeOutline, IoHardwareChipOutline, IoHeartOutline, IoHomeOutline, IoHourglassOutline, IoImageOutline, IoKeypadOutline, IoLanguageOutline, IoLayersOutline, IoLeafOutline, IoLinkOutline, IoLocation, IoLocationOutline, IoLockClosedOutline, IoLogOutOutline, IoLogoFacebook, IoLogoLinkedin, IoMailOutline, IoMegaphoneOutline, IoMoonOutline, IoMusicalNotesOutline, IoNotificationsOutline, IoOptionsOutline, IoPencil, IoPeopleOutline, IoPersonAddOutline, IoPersonOutline, IoPricetagOutline, IoQrCodeOutline, IoRefreshOutline, IoRemoveOutline, IoReorderThreeOutline, IoRestaurantOutline, IoRibbonOutline, IoRocketOutline, IoScanOutline, IoSchoolOutline, IoSearchOutline, IoShareSocialOutline, IoShieldCheckmarkOutline, IoShirtOutline, IoShuffleOutline, IoSparkles, IoSunnyOutline, IoTextOutline, IoTicketOutline, IoTimeOutline, IoTimerOutline, IoTrashOutline, IoTrophyOutline, IoWarningOutline, MdComputer, MdFormatBold, MdFormatItalic, MdInfo, MdLocationPin, MdOutlineArrowBack, RiDownloadFill, RiGithubFill, RiInstagramFill, RiInstagramLine, RiMenu3Line, RiTwitterFill, RiTwitterLine, TiTick
} = Object.fromEntries(Object.keys(iconMap).map((name) => [name, makeIcon(name)]));
